apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-dev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader-dev
  template:
    metadata:
      labels:
        app: uploader-dev
    spec:
      containers:
        - image: rsopix5/uploaderslik-uploader-dev:kube
          name: uploader-dev
          imagePullPolicy: Always
          env:
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd-server:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://35.240.79.227:8080
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://10.74.96.3:5432/submissions
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: test
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: uploader-dev
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: uploader-dev
